sonar.projectKey=gotodrop
sonar.organization=your-organization

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=GotoDrop
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=Backend/src/main,Frontend/src
sonar.tests=Backend/src/test

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.java.source=17

# Coverage
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=Backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=Frontend/coverage/lcov.info

# Exclusions
sonar.exclusions=**/*.test.ts,**/*.test.js,**/node_modules/**,**/target/**
